SECRET_KEY = "TMgW4cECe234i20945u3sRw*4!rP2352!$!$%&7ñPKNJNDFWOM9qnnf$B"
DATA_BASE = "data/users_thebridge.db"
MODEL = "data/model/model.pkl"
ENDPOINT = "Elasticpoc-env.eba-jdn63brc.eu-west-3.elasticbeanstalk.com"
HOST = "database-poc.ceeicqti4fmz.eu-west-3.rds.amazonaws.com"
USER = "adminpoc"
PASSWORD = "adminpoc"